namespace HpVictusControl;

public static partial class Loc {

    // English text → Arabic. Technical names stay in English inside the Arabic (CPU, GPU, RAM,
    // BIOS, NVIDIA, Intel, Hz, FPS, RPM, Wi-Fi, Steam, Windows…), the way they're written on the
    // hardware and in games. Numbers stay Western. Keys must match the English exactly; anything
    // missing here is simply shown in English.
    private static readonly Dictionary<string, string> Arabic = new() {

        // ----- Navigation and modes -----
        ["Performance"] = "الأداء",
        ["Balanced"] = "متوازن",
        ["Cool"] = "تبريد",
        ["Games"] = "الألعاب",
        ["Drivers"] = "التعريفات",
        ["System"] = "النظام",
        ["Settings"] = "الإعدادات",
        ["Default"] = "افتراضي",
        ["Auto"] = "تلقائي",
        ["Off"] = "متوقف",
        ["Apply"] = "تطبيق",
        ["Remove"] = "إزالة",
        ["Download"] = "تنزيل",
        ["Downloading..."] = "جارٍ التنزيل...",
        ["Retry"] = "إعادة المحاولة",
        ["Open folder"] = "فتح المجلد",
        ["Run installer"] = "تشغيل المثبّت",
        ["Installing..."] = "جارٍ التثبيت...",
        ["Installed"] = "تم التثبيت",
        ["Close"] = "إغلاق",
        ["Copy"] = "نسخ",
        ["Refresh"] = "تحديث",
        ["Reset"] = "إعادة تعيين",
        ["Clear"] = "مسح",
        ["Clean up"] = "تنظيف",
        ["Exit"] = "خروج",
        ["Yes (BIOS)"] = "نعم (BIOS)",
        ["No"] = "لا",

        // ----- Performance page -----
        ["Live stats"] = "القراءات المباشرة",
        ["Fan control"] = "التحكم بالمراوح",
        ["CPU FAN"] = "مروحة CPU",
        ["GPU FAN"] = "مروحة GPU",
        ["Max fan"] = "مروحة قصوى",
        ["Auto fan"] = "مروحة تلقائية",
        ["by temperature"] = "حسب الحرارة",
        ["Manual fan speed"] = "سرعة مروحة يدوية",
        ["Apply fan speed"] = "تطبيق سرعة المروحة",
        ["Auto-switch by power source"] = "التبديل التلقائي حسب مصدر الطاقة",
        ["Performance when plugged in, Cool on battery"] = "الأداء عند توصيل الشاحن، والتبريد على البطارية",
        ["Refresh rate"] = "معدل التحديث",
        ["Refresh rate in {0} mode"] = "معدل التحديث في وضع {0}",
        ["Battery time"] = "مدة البطارية",
        ["Everyday mix of speed and quiet"] = "توازن يومي بين السرعة والهدوء",
        ["Full speed, loudest and hottest"] = "أقصى سرعة، أعلى صوتًا وأكثر حرارة",
        ["Quietest, coolest, saves battery"] = "الأهدأ والأبرد، ويوفر البطارية",
        ["Runs both fans flat out"] = "يشغّل المروحتين بأقصى سرعة",
        ["Ramps each fan with its own temperature instead of the BIOS's built-in curve"] = "يرفع سرعة كل مروحة حسب حرارتها بدل منحنى BIOS المدمج",
        ["Not available — no NVIDIA GPU detected (reads via nvidia-smi)."] = "غير متاح — لم يُعثر على GPU من NVIDIA (القراءة عبر nvidia-smi).",
        ["Tip: press {0} anywhere to cycle performance mode"] = "تلميح: اضغط {0} في أي مكان للتنقل بين أوضاع الأداء",
        ["Tip: press Ctrl+Alt+F12 anywhere to cycle performance mode"] = "تلميح: اضغط Ctrl+Alt+F12 في أي مكان للتنقل بين أوضاع الأداء",
        ["Closing this window minimizes to the tray. Use the tray icon to exit."] = "إغلاق هذه النافذة ينقلها إلى منطقة الإشعارات. استخدم أيقونتها للخروج.",
        ["RAM {0:0.#} / {1:0.#} GB used"] = "المستخدم من RAM: {0:0.#} / {1:0.#} GB",
        ["{0} {1:0}% usage"] = "{0} استخدام {1:0}%",
        ["Battery not detected"] = "لم يتم العثور على البطارية",
        ["Charging"] = "قيد الشحن",
        ["Plugged in"] = "موصول بالشاحن",
        ["On battery"] = "على البطارية",
        ["Battery {0}%  ·  {1}"] = "البطارية {0}%  ·  {1}",
        ["About {0:0.0} W on average"] = "حوالي {0:0.0} واط في المتوسط",
        ["Not measured on battery yet"] = "لم يُقَس على البطارية بعد",
        ["From {0}% now."] = "من {0}% الآن.",
        ["If unplugged at {0}%."] = "بشحن {0}% إذا فُصل الشاحن الآن.",
        ["Learns each mode while you use it on battery."] = "يتعلّم كل وضع أثناء استخدامه على البطارية.",
        ["{0} — = not used on battery yet."] = "{0} — = لم يُستخدم على البطارية بعد.",
        ["Windows didn't accept {0}Hz for this display."] = "لم يقبل Windows معدل {0}Hz لهذه الشاشة.",
        ["Victus Hub  |  CPU {0}  CPU fan {1} GPU fan {2} RPM"] = "Victus Hub  |  CPU {0}  مروحة CPU {1}  مروحة GPU {2} RPM",
        ["Switched to {0} mode"] = "تم التبديل إلى وضع {0}",
        ["Windows' power plan had changed — put it back to {0} mode"] = "تغيّرت خطة الطاقة في Windows — أُعيدت إلى وضع {0}",
        ["{0} temperature is high: {1:0.#}°C"] = "حرارة {0} مرتفعة: {1:0.#} درجة",
        ["Max fan on"] = "المروحة القصوى: تشغيل",
        ["Max fan off"] = "المروحة القصوى: إيقاف",
        ["Shortcut: {0}"] = "الاختصار: {0}",
        ["This device doesn't expose the HP BIOS control interface this app relies on " +
         "(root\\wmi, class hpqBIntM). It's built for HP Omen/Victus laptops and needs to run as Administrator."] =
            "هذا الجهاز لا يوفّر واجهة التحكم في HP BIOS التي يعتمد عليها التطبيق (root\\wmi، الفئة hpqBIntM). " +
            "التطبيق مصمم لأجهزة HP Omen/Victus ويحتاج إلى التشغيل كمسؤول.",

        // ----- Games -----
        ["Mode, refresh rate and max fan switch on while a game runs and go back when it closes. The FPS cap is stored in the NVIDIA driver, the same as Control Panel's Max Frame Rate."] =
            "يتغير الوضع ومعدل التحديث والمروحة القصوى أثناء تشغيل اللعبة، وتعود كما كانت عند إغلاقها. يُحفظ حد FPS في تعريف NVIDIA، مثل خيار Max Frame Rate في لوحة التحكم.",
        ["Add game..."] = "إضافة لعبة...",
        ["Scan for games"] = "البحث عن ألعاب",
        ["Tune Wi-Fi while playing"] = "ضبط Wi-Fi أثناء اللعب",
        ["Add games as you play them"] = "إضافة الألعاب تلقائيًا عند تشغيلها",
        ["While any game in this list runs, stops Windows scanning for other Wi-Fi networks in the background — the usual cause of lag spikes that repeat about once a minute."] =
            "أثناء تشغيل أي لعبة في القائمة، يوقف بحث Windows عن شبكات Wi-Fi أخرى في الخلفية — وهو السبب المعتاد لارتفاعات التأخير التي تتكرر كل دقيقة تقريبًا.",
        ["When a game starts from a Steam, Epic, Xbox, GOG or Battle.net library and isn't in this list yet, it's added with nothing switched on."] =
            "عند تشغيل لعبة من مكتبة Steam أو Epic أو Xbox أو GOG أو Battle.net وليست في القائمة، تُضاف دون تفعيل أي خيار.",
        ["No games yet. Scan to find your Steam and Epic games."] = "لا توجد ألعاب بعد. ابحث للعثور على ألعاب Steam و Epic.",
        ["1 game"] = "لعبة واحدة",
        ["{0} games"] = "{0} ألعاب",
        ["Not found on this PC"] = "غير موجودة على هذا الجهاز",
        ["Mode"] = "الوضع",
        ["Resolution"] = "الدقة",
        ["Empty = no change"] = "فارغ = بدون تغيير",
        ["FPS cap"] = "حد FPS",
        ["Empty = no cap"] = "فارغ = بدون حد",
        ["Use NVIDIA GPU"] = "استخدام GPU من NVIDIA",
        ["Max fan while playing"] = "مروحة قصوى أثناء اللعب",
        ["Runs both fans flat out while this game is open, then puts the fans back afterwards"] = "يشغّل المروحتين بأقصى سرعة أثناء فتح هذه اللعبة، ثم يعيدهما كما كانتا بعدها",
        ["Game boost"] = "تعزيز اللعبة",
        ["While this game runs: gives it high CPU priority and closes OneDrive so syncing doesn't compete. Both go back when the game closes."] =
            "أثناء تشغيل هذه اللعبة: يمنحها أولوية CPU عالية ويغلق OneDrive حتى لا تنافسها المزامنة. يعود كلاهما عند إغلاق اللعبة.",
        ["Use the mode selected on the Performance page"] = "استخدام الوضع المحدد في صفحة الأداء",
        ["Keep the refresh rate that goes with the mode"] = "الإبقاء على معدل التحديث المرتبط بالوضع",
        ["Leave both empty to keep the desktop resolution while this game runs"] = "اترك الحقلين فارغين للإبقاء على دقة سطح المكتب أثناء تشغيل اللعبة",
        ["Enter a width and a height, for example 1280 × 720 — or clear both boxes to leave the resolution alone."] = "أدخل العرض والارتفاع، مثل 1280 × 720 — أو امسح الحقلين لترك الدقة كما هي.",
        ["This display has no {0} × {1} mode, so Windows would refuse to switch to it.\n\nSizes it does have:\n{2}"] =
            "هذه الشاشة لا تدعم الدقة {0} × {1}، لذا سيرفض Windows التبديل إليها.\n\nالدقات المدعومة:\n{2}",
        ["{0}–{1} fps, or empty for no cap"] = "{0}–{1} FPS، أو فارغ بدون حد",
        ["Enter a frame rate between {0} and {1}, or leave the box empty for no cap."] = "أدخل معدل إطارات بين {0} و {1}، أو اترك الحقل فارغًا بدون حد.",
        ["The NVIDIA driver didn't accept that frame rate limit."] = "لم يقبل تعريف NVIDIA حد الإطارات هذا.",
        ["Couldn't change the GPU preference: {0}"] = "تعذّر تغيير تفضيل GPU: {0}",
        ["Scanning Steam and Epic Games libraries..."] = "جارٍ البحث في مكتبات Steam و Epic Games...",
        ["No installed Steam or Epic games found."] = "لم يُعثر على ألعاب Steam أو Epic مثبّتة.",
        ["Found {0} installed game(s)"] = "تم العثور على {0} لعبة مثبّتة",
        ["{0} new"] = "{0} جديدة",
        ["{0} removed (uninstalled or duplicate)"] = "{0} أُزيلت (محذوفة أو مكررة)",
        ["no changes"] = "لا تغييرات",
        ["Scan failed: {0}"] = "فشل البحث: {0}",
        ["Added {0} to Games"] = "تمت إضافة {0} إلى الألعاب",
        ["Added {0} games: {1}"] = "تمت إضافة {0} ألعاب: {1}",
        ["{0} closed — restored {1} mode"] = "أُغلقت {0} — تمت استعادة وضع {1}",
        ["{0} mode"] = "وضع {0}",
        ["max fan"] = "المروحة القصوى",
        ["game boost"] = "تعزيز اللعبة",
        ["Wi-Fi tuning"] = "ضبط Wi-Fi",
        [", "] = "، ",
        ["{0} {1}"] = "{1}: {0}",
        ["  ·  "] = "، ",
        ["{0} detected — switched to {1}"] = "تم رصد {0} — التبديل إلى {1}",

        // ----- Drivers -----
        ["Driver & BIOS updates"] = "تحديثات التعريفات و BIOS",
        ["Looks up real updates for this exact laptop from HP, NVIDIA and Intel — nothing is installed automatically."] =
            "يبحث عن التحديثات الفعلية لهذا الجهاز تحديدًا من HP و NVIDIA و Intel — لا يُثبَّت شيء تلقائيًا.",
        ["Open downloads folder"] = "فتح مجلد التنزيلات",
        ["Check for updates"] = "البحث عن تحديثات",
        ["Checking..."] = "جارٍ الفحص...",
        ["Search updates"] = "بحث في التحديثات",
        ["Newest first"] = "الأحدث أولًا",
        ["Oldest first"] = "الأقدم أولًا",
        ["Name A→Z"] = "الاسم أبجديًا",
        ["By type"] = "حسب النوع",
        ["Largest first"] = "الأكبر أولًا",
        ["Click to change the order"] = "انقر لتغيير الترتيب",
        ["Select all"] = "تحديد الكل",
        ["Download selected"] = "تنزيل المحدد",
        ["Install selected"] = "تثبيت المحدد",
        ["Download selected ({0})"] = "تنزيل المحدد ({0})",
        ["Install selected ({0})"] = "تثبيت المحدد ({0})",
        ["{0} of {1} selected"] = "تم تحديد {0} من {1}",
        ["Tick updates to download or install several at once. Click an update for details."] =
            "حدّد التحديثات لتنزيل أو تثبيت عدة منها معًا. انقر على تحديث لعرض تفاصيله.",
        ["Show"] = "عرض",
        ["Type"] = "النوع",
        ["State"] = "الحالة",
        ["All updates"] = "كل التحديثات",
        ["Recommended"] = "الموصى بها",
        ["Firmware"] = "البرنامج الثابت",
        ["Software"] = "البرامج",
        ["Other"] = "أخرى",
        ["Downloaded"] = "المنزّلة",
        ["Graphics"] = "الرسوميات",
        ["Diagnostic"] = "تشخيص",
        ["Utility"] = "أداة",
        ["Audio"] = "صوت",
        ["Network"] = "شبكة",
        ["Storage"] = "التخزين",
        ["Driver"] = "تعريف",
        ["firmware"] = "برنامج ثابت",
        ["driver"] = "تعريف",
        ["drivers"] = "تعريفات",
        ["software"] = "برامج",
        ["other"] = "أخرى",
        ["Nothing matches this filter."] = "لا يوجد ما يطابق هذا التصنيف.",
        ["Click for details"] = "انقر لعرض التفاصيل",
        ["Offered version"] = "الإصدار المتاح",
        ["Installed now"] = "المثبّت حاليًا",
        ["Download size"] = "حجم التنزيل",
        ["Released"] = "تاريخ الإصدار",
        ["Source"] = "المصدر",
        ["File"] = "الملف",
        ["Saved to"] = "محفوظ في",
        ["Plug in the charger and leave it running. An interrupted BIOS update can leave the "
            + "laptop unable to boot — this app refuses to start one below 50% battery or on battery power."] =
            "صِل الشاحن واتركه موصولًا. انقطاع تحديث BIOS قد يمنع الجهاز من الإقلاع — هذا التطبيق يرفض بدء التحديث إذا كانت البطارية أقل من 50% أو بدون شاحن.",
        ["Firmware is written to the device itself. Keep the laptop powered while it installs."] =
            "يُكتب البرنامج الثابت على الجهاز نفسه. أبقِ الجهاز موصولًا بالطاقة أثناء التثبيت.",
        ["just now"] = "الآن",
        ["{0} min ago"] = "قبل {0} دقيقة",
        ["{0} hr ago"] = "قبل {0} ساعة",
        ["{0} day(s) ago"] = "قبل {0} يوم",
        ["Last checked {0}"] = "آخر فحص {0}",
        ["Checking HP's support site for your exact model..."] = "جارٍ فحص موقع دعم HP لطراز جهازك تحديدًا...",
        ["Checking NVIDIA directly for the real latest GPU driver..."] = "جارٍ فحص NVIDIA مباشرة لأحدث تعريف GPU فعلي...",
        ["Checking Intel directly for newer Intel drivers..."] = "جارٍ فحص Intel مباشرة لتعريفات Intel أحدث...",
        ["You're up to date"] = "جهازك محدّث",
        ["No newer drivers or BIOS found for this model."] = "لم يُعثر على تعريفات أو BIOS أحدث لهذا الطراز.",
        [" Intel confirms its latest is installed: {0}."] = " تؤكد Intel أن أحدث إصدار مثبّت: {0}.",
        ["1 update available"] = "تحديث واحد متاح",
        ["{0} updates available"] = "{0} تحديثات متاحة",
        ["Couldn't check for updates: {0}"] = "تعذّر البحث عن التحديثات: {0}",
        ["Unexpected error checking for updates: {0}"] = "خطأ غير متوقع أثناء البحث عن التحديثات: {0}",
        ["Download failed: {0}"] = "فشل التنزيل: {0}",
        ["Downloading {0} of {1}: {2}..."] = "جارٍ تنزيل {0} من {1}: {2}...",
        ["Downloaded {0} update(s)."] = "تم تنزيل {0} تحديث.",
        ["{0}\n\nNothing was installed."] = "{0}\n\nلم يُثبَّت أي شيء.",
        ["\n\nThis includes a BIOS update. Do not turn off, unplug, or close the lid during installation — " +
         "an interrupted BIOS update can leave the laptop unable to boot. Make sure it's plugged into AC power."] =
            "\n\nيتضمن ذلك تحديثًا لـ BIOS. لا تُطفئ الجهاز أو تفصل الشاحن أو تُغلق الغطاء أثناء التثبيت — انقطاع تحديث BIOS قد يمنع الجهاز من الإقلاع. تأكد من توصيله بالشاحن.",
        ["\n\nEach installer runs one after another; some may require a restart."] = "\n\nتعمل المثبّتات واحدًا تلو الآخر، وقد يتطلب بعضها إعادة التشغيل.",
        ["Install {0} update(s)?\n\n{1}{2}"] = "تثبيت {0} تحديث؟\n\n{1}{2}",
        ["Installing {0} of {1}: {2}..."] = "جارٍ تثبيت {0} من {1}: {2}...",
        ["Skipped {0}: {1}"] = "تم تخطي {0}: {1}",
        ["Installed {0} update(s) successfully."] = "تم تثبيت {0} تحديث بنجاح.",
        ["Installed {0} update(s); {1} didn't complete cleanly — check the individual row(s)."] = "تم تثبيت {0} تحديث؛ و{1} لم يكتمل بشكل سليم — راجع كل صف على حدة.",
        ["Couldn't run {0}: {1}"] = "تعذّر تشغيل {0}: {1}",
        ["BIOS updates only run on the charger. Plug the laptop in and try again."] = "تحديثات BIOS تعمل فقط مع الشاحن. صِل الجهاز بالشاحن وحاول مجددًا.",
        ["Windows can't read the battery level, so the BIOS update was blocked to be safe."] = "لا يستطيع Windows قراءة مستوى البطارية، لذا مُنع تحديث BIOS احتياطًا.",
        ["The battery is at {0}%. Let it charge to at least {1}% before a BIOS update, " +
         "so it can finish even if the charger gets unplugged."] =
            "البطارية عند {0}%. اشحنها إلى {1}% على الأقل قبل تحديث BIOS، حتى يكتمل التحديث حتى لو فُصل الشاحن.",
        ["This is a BIOS update. Do not turn off, unplug, or close the lid until it finishes — " +
         "an interrupted BIOS update can leave the laptop unable to boot.\n\nMake sure it's plugged into AC power first."] =
            "هذا تحديث لـ BIOS. لا تُطفئ الجهاز أو تفصل الشاحن أو تُغلق الغطاء حتى ينتهي — انقطاع تحديث BIOS قد يمنع الجهاز من الإقلاع.\n\nتأكد أولًا من توصيله بالشاحن.",
        ["This will launch the installer, which may require a restart to finish.\n\n" +
         "Many HP driver installers run silently with no visible window — this button will report when it's actually done."] =
            "سيبدأ تشغيل المثبّت، وقد يتطلب إعادة التشغيل للإكمال.\n\nكثير من مثبّتات تعريفات HP تعمل بصمت دون نافذة ظاهرة — سيُعلمك هذا الزر عند انتهائه فعليًا.",
        ["Run \"{0}\" now?\n\n{1}"] = "تشغيل \"{0}\" الآن؟\n\n{1}",
        ["{0} exited with code {1}. It may not have fully installed — " +
         "check the extracted files under C:\\SWSetup for its log, or try running it again."] =
            "{0} انتهى بالرمز {1}. قد لا يكون التثبيت اكتمل — راجع الملفات المستخرجة في C:\\SWSetup للاطلاع على السجل، أو أعد تشغيله.",

        // ----- System page -----
        ["This laptop"] = "هذا الجهاز",
        ["Reading system details…"] = "جارٍ قراءة تفاصيل النظام…",
        ["Check warranty"] = "فحص الضمان",
        ["Opens HP's warranty check page"] = "يفتح صفحة فحص الضمان من HP",
        ["Copy details"] = "نسخ التفاصيل",
        ["Model"] = "الطراز",
        ["Product number"] = "رقم المنتج",
        ["Serial number"] = "الرقم التسلسلي",
        ["Processor"] = "المعالج",
        ["Memory"] = "الذاكرة",
        ["Display"] = "الشاشة",
        ["Graphics switch"] = "مبدّل الرسوميات",
        ["Handy for support chats, warranty checks and forum posts."] = "مفيدة لمحادثات الدعم وفحص الضمان والمنتديات.",
        ["Couldn't read the system details."] = "تعذّرت قراءة تفاصيل النظام.",
        ["Copied — paste it anywhere."] = "تم النسخ — الصقه في أي مكان.",
        ["The clipboard was busy — try again."] = "الحافظة مشغولة — حاول مجددًا.",
        ["Battery health"] = "صحة البطارية",
        ["Reading the battery report…"] = "جارٍ قراءة تقرير البطارية…",
        ["Windows didn't return a battery report for this PC."] = "لم يُرجع Windows تقريرًا للبطارية على هذا الجهاز.",
        ["Healthy — close to new"] = "سليمة — قريبة من الجديدة",
        ["Normal wear"] = "تآكل طبيعي",
        ["Worn — expect noticeably shorter battery life"] = "متآكلة — توقّع عمر بطارية أقصر بشكل ملحوظ",
        ["{0}. Holds {1:0.0} Wh of the {2:0.0} Wh it had when new."] = "{0}. تتسع لـ {1:0.0} واط ساعة من أصل {2:0.0} واط ساعة عندما كانت جديدة.",
        ["{0} charge cycles"] = "{0} دورة شحن",
        ["Lithium-ion"] = "ليثيوم أيون",
        ["{0:0.0} Wh on {1:MMM d}"] = "{0:0.0} واط ساعة في {1:d/M}",
        ["Plugged in {0:P0} of the time recently. Batteries wear fastest when held at 100%: " +
         "if your BIOS setup has HP's Adaptive Battery Optimizer, turning it on lets the laptop hold a lower charge while it stays plugged in."] =
            "كان موصولًا بالشاحن {0:P0} من الوقت مؤخرًا. تتآكل البطاريات أسرع عند بقائها على 100%: " +
            "إذا كان إعداد BIOS يحتوي على Adaptive Battery Optimizer من HP، فتفعيله يجعل الجهاز يحافظ على شحن أقل أثناء بقائه موصولًا.",
        ["Drive health"] = "صحة القرص",
        ["{0}% write endurance left"] = "متبقٍ {0}% من عمر الكتابة",
        ["{0:N0} hours powered on"] = "{0:N0} ساعة تشغيل",
        ["rated max {0}°C"] = "الحد المقرر {0} درجة",
        ["{0:N0} read/write errors"] = "{0:N0} خطأ قراءة/كتابة",
        ["This drive doesn't report health counters."] = "هذا القرص لا يوفّر عدادات الصحة.",
        ["Running hot — it will throttle to protect itself. Check airflow and the vents."] = "حرارته مرتفعة — سيخفض سرعته لحماية نفسه. تحقق من التهوية وفتحات الهواء.",
        ["Nearly out of rated write endurance. Back up and plan a replacement."] = "اقترب من نهاية عمر الكتابة المقرر. احتفظ بنسخة احتياطية وخطط لاستبداله.",
        ["The drive has logged read/write errors. Back up anything important."] = "سجّل القرص أخطاء قراءة/كتابة. احتفظ بنسخة احتياطية من ملفاتك المهمة.",
        ["Graphics mode"] = "وضع الرسوميات",
        ["Checking the BIOS…"] = "جارٍ فحص BIOS…",
        ["Hybrid"] = "هجين",
        ["NVIDIA only"] = "NVIDIA فقط",
        ["Intel GPU drives the screen, NVIDIA renders games. Longer battery life."] = "معالج Intel الرسومي يشغّل الشاشة و NVIDIA يعالج الألعاب. عمر أطول للبطارية.",
        ["NVIDIA GPU drives the screen directly. More fps, shorter battery life."] = "معالج NVIDIA الرسومي يشغّل الشاشة مباشرة. FPS أعلى وعمر أقصر للبطارية.",
        ["Restart now"] = "إعادة التشغيل الآن",
        ["Needs the HP BIOS interface, which isn't available right now."] = "يحتاج إلى واجهة HP BIOS، وهي غير متاحة حاليًا.",
        ["The BIOS didn't answer the graphics switch query."] = "لم يستجب BIOS لاستعلام مبدّل الرسوميات.",
        ["This laptop doesn't have a graphics switch: its BIOS reports no MUX. The Intel GPU always drives the built-in " +
         "screen and the NVIDIA GPU renders games through it. That's wired into the hardware, so no app or setting can change it — " +
         "\"Use NVIDIA GPU\" on each game is already the fastest option available."] =
            "لا يحتوي هذا الجهاز على مبدّل رسوميات: يُبلغ BIOS عن عدم وجود MUX. معالج Intel الرسومي يشغّل الشاشة المدمجة دائمًا " +
            "ومعالج NVIDIA يعالج الألعاب من خلاله. هذا مدمج في العتاد، فلا يمكن لأي تطبيق أو إعداد تغييره — " +
            "خيار \"استخدام GPU من NVIDIA\" لكل لعبة هو أسرع خيار متاح.",
        ["This laptop has a graphics switch, but the BIOS didn't report its current mode."] = "يحتوي هذا الجهاز على مبدّل رسوميات، لكن BIOS لم يُبلغ عن وضعه الحالي.",
        ["Hybrid lets the Intel GPU run the screen and hands game frames over from NVIDIA — better battery life. " +
         "NVIDIA only connects the screen straight to the NVIDIA GPU — more fps, but the battery drains faster. Takes effect after a restart."] =
            "الوضع الهجين يجعل معالج Intel الرسومي يشغّل الشاشة ويستلم إطارات الألعاب من NVIDIA — عمر أفضل للبطارية. " +
            "وضع NVIDIA فقط يوصل الشاشة مباشرة بمعالج NVIDIA — FPS أعلى لكن البطارية تنفد أسرع. يُطبَّق بعد إعادة التشغيل.",
        ["Switch graphics mode to {0}?\n\nThe BIOS applies this the next time the laptop restarts."] =
            "تبديل وضع الرسوميات إلى {0}؟\n\nسيطبّق BIOS ذلك عند إعادة تشغيل الجهاز القادمة.",
        ["\n\nNVIDIA only drains the battery noticeably faster."] = "\n\nوضع NVIDIA فقط يستنزف البطارية أسرع بشكل ملحوظ.",
        ["{0} is set and will be used after you restart."] = "تم ضبط {0} وسيُستخدم بعد إعادة التشغيل.",
        ["The BIOS didn't accept the change: {0}"] = "لم يقبل BIOS التغيير: {0}",
        ["Restart the laptop now? Save anything you have open first."] = "إعادة تشغيل الجهاز الآن؟ احفظ أي عمل مفتوح أولًا.",
        ["Couldn't restart: {0}"] = "تعذّرت إعادة التشغيل: {0}",
        ["Maintenance"] = "الصيانة",
        ["Fan test"] = "اختبار المراوح",
        ["Runs both fans at full speed for 15 seconds and checks they spin up properly"] = "يشغّل المروحتين بأقصى سرعة لمدة 15 ثانية ويتحقق من دورانهما بشكل صحيح",
        ["Test fans"] = "اختبار المراوح",
        ["Measuring…"] = "جارٍ القياس…",
        ["Shader cache"] = "ذاكرة Shader المؤقتة",
        ["Driver downloads"] = "تنزيلات التعريفات",
        ["Clean up automatically"] = "تنظيف تلقائي",
        ["Deletes each installer once it has installed successfully, and any left over for 30 days"] = "يحذف كل مثبّت بعد نجاح تثبيته، وأي مثبّت متبقٍ منذ 30 يومًا",
        ["Empty. Games rebuild it as they run."] = "فارغة. تعيد الألعاب بناءها أثناء التشغيل.",
        ["{0} of compiled NVIDIA, DirectX and Intel shaders. Clearing it can fix stutter after a driver update; games rebuild it, so their next launch loads a little slower."] =
            "{0} من shaders المترجمة لـ NVIDIA و DirectX و Intel. مسحها قد يعالج التقطيع بعد تحديث التعريف؛ تعيد الألعاب بناءها، لذا يكون تحميلها التالي أبطأ قليلًا.",
        ["No installers kept."] = "لا توجد مثبّتات محفوظة.",
        ["{0} in {1} installer(s) downloaded from the Drivers tab."] = "{0} في {1} مثبّت تم تنزيلها من صفحة التعريفات.",
        ["Clearing…"] = "جارٍ المسح…",
        ["Shader cache cleared — freed {0}"] = "تم مسح ذاكرة Shader — تم تحرير {0}",
        [" ({0} file(s) in use by a running game were left)"] = " (تُرك {0} ملف تستخدمه لعبة قيد التشغيل)",
        ["Delete every downloaded driver and BIOS installer? You can download them again from the Drivers tab."] =
            "حذف كل مثبّتات التعريفات و BIOS المنزّلة؟ يمكنك تنزيلها مجددًا من صفحة التعريفات.",
        ["Freed {0}"] = "تم تحرير {0}",
        ["; {0} installer(s) still in use were left"] = "؛ تُرك {0} مثبّت لا يزال قيد الاستخدام",
        ["Testing… {0}s"] = "جارٍ الاختبار… {0} ث",
        ["CPU fan ~{0:N0} RPM  ·  GPU fan ~{1:N0} RPM"] = "مروحة CPU {0:N0} RPM  ·  مروحة GPU {1:N0} RPM",
        // Alexandria draws "~" like a minus sign, which would make "~2200 RPM" read as negative.
        ["~{0} RPM"] = "{0} RPM",
        ["{0}: ~{1:N0} → ~{2:N0} RPM"] = "{0}: {1:N0} ← {2:N0} RPM",
        ["CPU fan"] = "مروحة CPU",
        ["GPU fan"] = "مروحة GPU",
        ["The BIOS didn't answer during the test: {0}"] = "لم يستجب BIOS أثناء الاختبار: {0}",
        ["{0}  ✗  didn't reach full speed — worth checking for dust or a failing fan."] = "{0}  ✗  لم تصل إلى السرعة القصوى — يُستحسن فحص الغبار أو احتمال تلف المروحة.",
        ["{0}  ⚠  noticeably slower than the other fan."] = "{0}  ⚠  أبطأ بشكل ملحوظ من المروحة الأخرى.",
        ["{0}  ✓  healthy, full speed within {1} s."] = "{0}  ✓  سليمة، وصلت للسرعة القصوى خلال {1} ث.",
        ["{0}  ✓  healthy."] = "{0}  ✓  سليمة.",

        // ----- Settings -----
        ["Appearance"] = "المظهر",
        ["Match Windows' light or dark theme"] = "مطابقة الوضع الفاتح أو الداكن في Windows",
        ["Switches along with Windows (Settings → Personalization → Colors)"] = "يتبدل مع Windows (الإعدادات ← التخصيص ← الألوان)",
        ["Dark theme"] = "الوضع الداكن",
        ["Interface size"] = "حجم الواجهة",
        ["Grows and shrinks with the window"] = "يكبر ويصغر مع النافذة",
        ["A fixed size, whatever the window size"] = "حجم ثابت مهما كان حجم النافذة",
        ["Scales text, icons and buttons with the window — now {0:0}%"] = "يغيّر حجم النصوص والأيقونات والأزرار مع النافذة — الآن {0:0}%",
        ["Language"] = "اللغة",
        ["Arabic uses a right-to-left layout. Applies after a restart."] = "العربية تستخدم تخطيطًا من اليمين إلى اليسار. يُطبَّق بعد إعادة التشغيل.",
        ["Always on top"] = "دائمًا في المقدمة",
        ["Sound"] = "الصوت",
        ["Keep speakers awake"] = "إبقاء السماعات نشطة",
        ["Stops the audio chip powering down after a few seconds of silence, which makes the next sound (like a UAC prompt's) start late. Uses a little more battery, and a Realtek driver update may undo it."] =
            "يمنع شريحة الصوت من إيقاف نفسها بعد ثوانٍ من الصمت، وهو ما يؤخر بدء الصوت التالي (مثل صوت نافذة UAC). يستهلك بطارية أكثر قليلًا، وقد يلغيه تحديث لتعريف Realtek.",
        ["Restart Windows to apply this."] = "أعد تشغيل Windows لتطبيق ذلك.",
        ["Couldn't change the speaker setting: {0}"] = "تعذّر تغيير إعداد السماعات: {0}",
        ["Keyboard shortcuts"] = "اختصارات لوحة المفاتيح",
        ["These work anywhere, even in a game. Click a shortcut, then press the new keys — it needs Ctrl, Alt or Win. Backspace turns it off, Esc cancels."] =
            "تعمل في أي مكان، حتى داخل اللعبة. انقر على اختصار ثم اضغط المفاتيح الجديدة — يجب أن يتضمن Ctrl أو Alt أو Win. زر Backspace يوقفه و Esc يلغي.",
        ["Toggle max fan"] = "تشغيل/إيقاف المروحة القصوى",
        ["Turns max fan speed on or off"] = "يشغّل أو يوقف أقصى سرعة للمروحة",
        ["Cycle performance mode"] = "التنقل بين أوضاع الأداء",
        ["Balanced → Performance → Cool"] = "متوازن ← الأداء ← تبريد",
        ["cycle performance mode"] = "التنقل بين أوضاع الأداء",
        ["toggle max fan"] = "تشغيل/إيقاف المروحة القصوى",
        ["Press keys…"] = "اضغط المفاتيح…",
        ["Shortcut turned off."] = "تم إيقاف الاختصار.",
        ["Another app already uses {0}. Pick a different shortcut below."] = "تطبيق آخر يستخدم {0} بالفعل. اختر اختصارًا آخر أدناه.",
        [" and "] = " و",
        ["{0} would block that key everywhere — hold Ctrl, Alt or Win as well."] = "{0} سيحجز هذا المفتاح في كل مكان — اضغط معه Ctrl أو Alt أو Win.",
        ["{0} is already the other shortcut."] = "{0} مستخدم بالفعل للاختصار الآخر.",
        ["{0} is already taken by Windows or another app. Try a different combination."] = "{0} محجوز من Windows أو تطبيق آخر. جرّب تركيبة مختلفة.",
        ["Saved: {0}"] = "تم الحفظ: {0}",
        ["Alerts & startup"] = "التنبيهات وبدء التشغيل",
        ["Start with Windows (minimized to tray)"] = "التشغيل مع Windows (في منطقة الإشعارات)",
        ["Couldn't update startup setting: {0}"] = "تعذّر تحديث إعداد بدء التشغيل: {0}",
        ["Exit instead of minimizing to tray when closed"] = "الخروج عند الإغلاق بدل الانتقال إلى منطقة الإشعارات",
        ["Notify when CPU or GPU gets too hot"] = "التنبيه عند ارتفاع حرارة CPU أو GPU",
        ["Threshold"] = "الحد",
        ["About & support"] = "حول التطبيق والدعم",
        ["Version {0}"] = "الإصدار {0}",
        ["Check for app updates"] = "البحث عن تحديثات للتطبيق",
        ["View release"] = "عرض الإصدار",
        ["Update now"] = "التحديث الآن",
        ["Update now ({0})"] = "التحديث الآن ({0})",
        ["Downloads the new build and puts it in place of this one"] = "ينزّل الإصدار الجديد ويضعه مكان هذا الإصدار",
        ["Checking for updates..."] = "جارٍ البحث عن تحديثات...",
        ["You're up to date."] = "لديك أحدث إصدار.",
        ["Version {0} is available (you have {1})."] = "الإصدار {0} متاح (لديك {1}).",
        ["Version {0} is available — Settings ▸ About to install it"] = "الإصدار {0} متاح — الإعدادات ◂ حول التطبيق لتثبيته",
        ["Downloading version {0}..."] = "جارٍ تنزيل الإصدار {0}...",
        ["Version {0} is installed. Restart Victus Hub now to use it?"] = "تم تثبيت الإصدار {0}. إعادة تشغيل Victus Hub الآن لاستخدامه؟",
        ["Version {0} installed — restart to use it."] = "تم تثبيت الإصدار {0} — أعد التشغيل لاستخدامه.",
        ["Update failed: {0}"] = "فشل التحديث: {0}",
        ["No release found. If the repository is private, its releases aren't readable without signing in."] =
            "لم يُعثر على إصدار. إذا كان المستودع خاصًا فلا يمكن قراءة إصداراته دون تسجيل الدخول.",
        ["GitHub returned {0}."] = "أعاد GitHub الرمز {0}.",
        ["Couldn't parse the latest release's version number."] = "تعذّرت قراءة رقم إصدار آخر نسخة.",
        ["That release has no downloadable build attached."] = "هذا الإصدار لا يحتوي على نسخة قابلة للتنزيل.",
        ["The download stopped early ({0:N0} of {1:N0} bytes)."] = "توقف التنزيل مبكرًا ({0:N0} من {1:N0} بايت).",
        ["This build can't replace itself."] = "هذه النسخة لا تستطيع استبدال نفسها.",
        ["The downloaded build is missing."] = "النسخة المنزّلة مفقودة.",
        ["Copy diagnostics"] = "نسخ بيانات التشخيص",
        ["Copies hardware, driver, and live sensor info to the clipboard for bug reports."] = "ينسخ معلومات العتاد والتعريفات والحساسات إلى الحافظة لإرفاقها مع بلاغات الأخطاء.",
        ["Diagnostics copied to clipboard."] = "تم نسخ بيانات التشخيص إلى الحافظة.",
        ["Couldn't copy diagnostics: {0}"] = "تعذّر نسخ بيانات التشخيص: {0}",
        ["Reset to defaults"] = "استعادة الإعدادات الافتراضية",
        ["Resets all app preferences (theme, auto-switch, fan curve, alerts, game profiles) back to defaults."] =
            "يعيد كل تفضيلات التطبيق (المظهر، التبديل التلقائي، منحنى المروحة، التنبيهات، ملفات الألعاب) إلى الوضع الافتراضي.",
        ["This resets all app preferences — theme, performance mode, auto-switch, fan curve, alerts, and " +
         "game profiles — back to defaults. Restart Victus Hub afterward for it to fully take effect. Continue?"] =
            "سيعيد هذا كل تفضيلات التطبيق — المظهر ووضع الأداء والتبديل التلقائي ومنحنى المروحة والتنبيهات وملفات الألعاب — إلى الوضع الافتراضي. " +
            "أعد تشغيل Victus Hub بعدها ليكتمل التطبيق. هل تريد المتابعة؟",
        ["Defaults restored. Restart Victus Hub for the change to fully take effect."] = "تمت استعادة الإعدادات الافتراضية. أعد تشغيل Victus Hub ليكتمل التغيير.",
        ["Still running in the background. Right-click the tray icon to exit."] = "ما زال يعمل في الخلفية. انقر بزر الفأرة الأيمن على الأيقونة للخروج.",

        // ----- BIOS settings -----
        ["BIOS settings"] = "إعدادات BIOS",
        ["The same options as the BIOS setup screen. Changes are saved to the BIOS and take effect after a restart."] =
            "نفس خيارات شاشة إعداد BIOS. تُحفظ التغييرات في BIOS وتُطبَّق بعد إعادة التشغيل.",
        ["Restart into BIOS"] = "إعادة التشغيل إلى BIOS",
        ["Restarts straight into the BIOS setup screen"] = "يعيد التشغيل مباشرة إلى شاشة إعداد BIOS",
        ["Restart to apply"] = "إعادة التشغيل للتطبيق",
        ["This laptop's BIOS doesn't share its settings with Windows. Use Restart into BIOS to change them there."] =
            "BIOS في هذا الجهاز لا يشارك إعداداته مع Windows. استخدم «إعادة التشغيل إلى BIOS» لتغييرها هناك.",
        ["A BIOS setup password is set, so these can only be changed in the BIOS screen."] =
            "تم تعيين كلمة مرور لإعداد BIOS، لذا لا يمكن تغيير هذه الخيارات إلا من شاشة BIOS.",
        ["Active now: the battery is being held below full charge."] = "مفعّلة الآن: تُبقي البطارية دون الشحن الكامل.",
        ["Not active yet: HP starts it once the laptop has been plugged in for a few days."] =
            "غير مفعّلة بعد: تبدأ HP تشغيلها بعد بقاء الجهاز موصولًا بالشاحن لبضعة أيام.",
        ["Battery care"] = "العناية بالبطارية",
        ["Holds the battery below full charge while the laptop stays plugged in, which slows wear. HP calls it Adaptive Battery Extender."] =
            "تُبقي البطارية دون الشحن الكامل أثناء بقاء الجهاز موصولًا بالشاحن، مما يبطئ تآكلها. تسميها HP باسم Adaptive Battery Extender.",
        ["Fans always on"] = "المراوح تعمل دائمًا",
        ["Keeps the fans turning slowly even when the laptop is cool. Off lets them stop at idle for silence."] =
            "تُبقي المراوح تدور ببطء حتى عندما يكون الجهاز باردًا. عند الإيقاف تتوقف أثناء الخمول لهدوء تام.",
        ["Action keys without Fn"] = "مفاتيح الإجراءات بدون Fn",
        ["On: the top row controls brightness, volume and so on. Off: it's F1–F12, and Fn gives the actions."] =
            "عند التشغيل: الصف العلوي يتحكم بالسطوع والصوت وغيرهما. عند الإيقاف: يعمل كمفاتيح F1–F12، و Fn يعطي الإجراءات.",
        ["Boot menu delay"] = "مهلة قائمة الإقلاع",
        ["{0} s"] = "{0} ث",
        ["How long the startup screen waits for Esc or F10. A few seconds makes the BIOS easier to reach."] =
            "مدة انتظار شاشة بدء التشغيل لمفتاح Esc أو F10. بضع ثوانٍ تجعل الوصول إلى BIOS أسهل.",
        ["On"] = "تشغيل",
        ["Change \"{0}\" to {1} in the BIOS?\n\nIt's saved to the BIOS straight away and takes effect after the next restart."] =
            "تغيير «{0}» إلى {1} في BIOS؟\n\nيُحفظ في BIOS فورًا ويُطبَّق بعد إعادة التشغيل القادمة.",
        ["Saved to the BIOS. Restart the laptop to apply it."] = "تم الحفظ في BIOS. أعد تشغيل الجهاز لتطبيقه.",
        ["Couldn't change the BIOS setting: {0}"] = "تعذّر تغيير إعداد BIOS: {0}",
        ["Restart straight into the BIOS setup screen now? Save anything you have open first."] =
            "إعادة التشغيل مباشرة إلى شاشة إعداد BIOS الآن؟ احفظ أي عمل مفتوح أولًا.",
        ["The BIOS doesn't support changing this setting."] = "لا يدعم BIOS تغيير هذا الإعداد.",
        ["The BIOS didn't respond in time."] = "لم يستجب BIOS في الوقت المحدد.",
        ["The BIOS rejected that value."] = "رفض BIOS هذه القيمة.",
        ["The BIOS asks for a setup password for this change."] = "يطلب BIOS كلمة مرور الإعداد لهذا التغيير.",
        ["The BIOS reported error {0}."] = "أبلغ BIOS عن الخطأ {0}.",

        // ----- Weekly driver check -----
        ["New driver update: {0}"] = "تحديث تعريف جديد: {0}",
        ["{0} new driver updates: {1}"] = "{0} تحديثات تعريفات جديدة: {1}",
        ["Check for driver updates every week"] = "البحث عن تحديثات التعريفات كل أسبوع",
        ["Checks HP, NVIDIA and Intel in the background and tells you when something new turns up. Nothing is installed without you."] =
            "يفحص HP و NVIDIA و Intel في الخلفية ويُعلمك عند ظهور شيء جديد. لا يُثبَّت أي شيء دون موافقتك.",

        // ----- What's new -----
        ["What's new in {0}"] = "الجديد في الإصدار {0}",
        ["Got it"] = "حسنًا",
        ["Linen light and dark themes, easier on the eyes over long sessions"] = "مظهر Linen بوضعيه الفاتح والداكن، أريح للعين في الجلسات الطويلة",
        ["Arabic interface with a right-to-left layout (Settings → Language)"] = "واجهة عربية بتخطيط من اليمين إلى اليسار (الإعدادات ← اللغة)",
        ["The interface scales with the window, from small to maximized"] = "حجم الواجهة يتغير مع النافذة، من الصغيرة إلى المكبّرة",
        ["Battery time for each performance mode, learned from how you use it"] = "مدة البطارية لكل وضع أداء، يتعلمها التطبيق من استخدامك",
        ["Drive health and BIOS settings on the System page, including battery care"] = "صحة القرص وإعدادات BIOS في صفحة النظام، ومنها العناية بالبطارية",
        ["Games are added to the list the first time you play them"] = "تُضاف الألعاب إلى القائمة عند تشغيلها أول مرة",
        ["The Drivers page remembers the last check, hides firmware for drives you don't have, and checks weekly"] =
            "صفحة التعريفات تتذكر آخر فحص، وتخفي البرامج الثابتة لأقراص غير موجودة، وتفحص أسبوعيًا",
        ["The app can download and install its own updates"] = "يستطيع التطبيق تنزيل تحديثاته وتثبيتها بنفسه",
        ["Fixed: the CPU dial drew outside its card above 50°C"] = "إصلاح: مؤشر CPU كان يُرسم خارج بطاقته فوق 50 درجة",

        // ----- Installing -----
        ["Installation"] = "التثبيت",
        ["Install"] = "تثبيت",
        ["Uninstall..."] = "إلغاء التثبيت...",
        ["Installed in {0}. Remove it from here or from Windows' installed apps."] = "مثبّت في {0}. يمكنك إزالته من هنا أو من التطبيقات المثبّتة في Windows.",
        ["Version {0} is installed in Program Files. This copy is running from {1}."] = "الإصدار {0} مثبّت في Program Files. هذه النسخة تعمل من {1}.",
        ["Not installed: running from {0}. Installing adds it to Program Files, the Start menu and Windows' installed apps."] =
            "غير مثبّت: يعمل من {0}. التثبيت يضيفه إلى Program Files وقائمة ابدأ والتطبيقات المثبّتة في Windows.",
        ["Update the installed Victus Hub from {0} to {1}?"] = "تحديث Victus Hub المثبّت من {0} إلى {1}؟",
        ["Install Victus Hub on this PC?\n\nIt's copied to Program Files, gets a Start menu shortcut and appears in Windows' installed apps, so it can be removed cleanly. You can also do this later in Settings → About."] =
            "تثبيت Victus Hub على هذا الجهاز؟\n\nيُنسخ إلى Program Files ويحصل على اختصار في قائمة ابدأ ويظهر في التطبيقات المثبّتة في Windows، لتتمكن من إزالته بشكل نظيف. يمكنك فعل ذلك لاحقًا من الإعدادات ← حول التطبيق.",
        ["Couldn't start the uninstall: {0}"] = "تعذّر بدء إلغاء التثبيت: {0}",
        ["Installed. Victus Hub is in the Start menu and Windows' installed apps."] = "تم التثبيت. Victus Hub موجود في قائمة ابدأ والتطبيقات المثبّتة في Windows.",
        ["Installed. Victus Hub will now restart from Program Files."] = "تم التثبيت. سيُعاد تشغيل Victus Hub الآن من Program Files.",
        ["Couldn't install: {0}"] = "تعذّر التثبيت: {0}",
        ["Uninstall Victus Hub?\n\nThe fans and performance mode go back to the BIOS defaults, and the startup task, shortcut and app files are removed."] =
            "إلغاء تثبيت Victus Hub؟\n\nتعود المراوح ووضع الأداء إلى إعدادات BIOS الافتراضية، وتُحذف مهمة بدء التشغيل والاختصار وملفات التطبيق.",
        ["Also delete your settings and game profiles?\n\nKeep them if you might install the app again."] =
            "حذف إعداداتك وملفات الألعاب أيضًا؟\n\nاحتفظ بها إذا كنت قد تثبّت التطبيق مجددًا.",
        ["Victus Hub has been uninstalled."] = "تم إلغاء تثبيت Victus Hub.",

        // ----- Crash notice -----
        ["Victus Hub closed unexpectedly last time"] = "أُغلق Victus Hub بشكل غير متوقع في المرة السابقة",
        ["Copy report"] = "نسخ التقرير",
        ["Dismiss"] = "إخفاء",
        ["{0} — {1}. The full report is saved in {2}."] = "{0} — {1}. التقرير الكامل محفوظ في {2}.",
        ["Report copied — paste it into a bug report or a message."] = "تم نسخ التقرير — الصقه في بلاغ خطأ أو رسالة.",

        // ----- Compatibility -----
        ["Supported here"] = "المدعوم هنا",
        ["Fan and performance control"] = "التحكم بالمراوح والأداء",
        // ----- Tray menu -----
        ["Open Victus Hub"] = "فتح Victus Hub",
        ["Max fan speed"] = "أقصى سرعة للمروحة",
        ["Performance mode"] = "وضع الأداء",

        // ----- GPU power and idle -----
        ["GPU power"] = "طاقة GPU",
        ["Higher power limit"] = "حد طاقة أعلى",
        ["Lets the NVIDIA GPU draw more power (custom TGP): more fps, more heat"] = "يسمح لكرت NVIDIA بسحب طاقة أكبر (custom TGP): إطارات أكثر وحرارة أعلى",
        ["Dynamic Boost"] = "Dynamic Boost",
        ["Moves power from the CPU to the GPU when the CPU doesn't need it"] = "ينقل الطاقة من المعالج إلى كرت الشاشة عندما لا يحتاجها المعالج",
        ["Applied."] = "تم التطبيق.",
        ["The BIOS didn't take that change."] = "لم يقبل الـ BIOS هذا التغيير.",
        ["When you step away"] = "عند الابتعاد عن الجهاز",
        ["Cool mode when idle"] = "وضع التبريد عند الخمول",
        ["Quiets the fans after no mouse or keyboard input, and switches back as soon as you return. Not while a game from your list is running."] =
            "يهدّئ المراوح عند عدم استخدام الفأرة أو لوحة المفاتيح، ويعود فور رجوعك. لا يعمل أثناء تشغيل لعبة من قائمتك.",
        ["2 min"] = "2 دقيقة",
        ["5 min"] = "5 دقائق",
        ["10 min"] = "10 دقائق",
        ["20 min"] = "20 دقيقة",
        ["1 min"] = "دقيقة",
        ["30 s"] = "30 ثانية",
        ["Never"] = "أبدًا",
        ["Keyboard backlight"] = "إضاءة لوحة المفاتيح",
        ["Turn it off after no input for"] = "إطفاؤها بعد عدم الاستخدام لمدة",
        ["{0}, Cool while idle"] = "{0}، تبريد أثناء الخمول",
        ["The download doesn't match the release's checksum, so it wasn't used."] = "الملف المحمّل لا يطابق checksum الإصدار، لذلك لم يُستخدم.",
        // ----- CPU power, GPU performance, restore points, startup apps, camera -----
        ["CPU power"] = "طاقة CPU",
        ["How much power the CPU may keep drawing under long loads (PL1) in Performance mode. Higher holds clock speeds up longer, and runs hotter."] =
            "مقدار الطاقة التي يستطيع المعالج سحبها باستمرار تحت الحمل الطويل (PL1) في وضع الأداء. القيمة الأعلى تحافظ على السرعة لمدة أطول، مع حرارة أعلى.",
        ["Using the laptop's own limit for each mode."] = "يُستخدم حد الجهاز الافتراضي لكل وضع.",
        ["{0} W is used in Performance mode."] = "يُستخدم {0} واط في وضع الأداء.",
        ["{0} W applied. If the CPU stays at {1}°C, it's lowered to {2} W until the next mode change."] =
            "تم تطبيق {0} واط. إذا بقي المعالج عند {1} درجة، يُخفَّض إلى {2} واط حتى تغيير الوضع التالي.",
        ["The CPU stayed at {0}°C, so its limit was lowered to {1} W until the next mode change."] =
            "بقي المعالج عند {0} درجة، فخُفّض حده إلى {1} واط حتى تغيير الوضع التالي.",
        ["CPU at {0}°C: power limit lowered to {1} W"] = "المعالج عند {0} درجة: خُفّض حد الطاقة إلى {1} واط",
        ["Max GPU performance"] = "أقصى أداء لكرت الشاشة",
        ["Keeps the NVIDIA GPU at full clocks while this game runs, for steadier frame times. Stored in the NVIDIA driver, the same as Control Panel's \"Prefer maximum performance\". Uses more power."] =
            "يبقي كرت NVIDIA على أعلى سرعة أثناء تشغيل هذه اللعبة لإطارات أكثر ثباتًا. يُحفظ في تعريف NVIDIA مثل خيار \"Prefer maximum performance\" في لوحة التحكم. يستهلك طاقة أكثر.",
        ["The NVIDIA driver didn't accept the change."] = "لم يقبل تعريف NVIDIA هذا التغيير.",
        ["Create a restore point before installing"] = "إنشاء نقطة استعادة قبل التثبيت",
        ["Makes a Windows restore point first, so a driver or BIOS update that causes problems can be undone from System Restore. Windows makes at most one a day."] =
            "ينشئ نقطة استعادة في Windows أولًا، ليمكن التراجع عن أي تحديث تعريف أو BIOS يسبب مشاكل من استعادة النظام. ينشئ Windows نقطة واحدة يوميًا كحد أقصى.",
        ["Creating a restore point… this can take a minute."] = "جارٍ إنشاء نقطة استعادة… قد يستغرق ذلك دقيقة.",
        ["Restore point created."] = "تم إنشاء نقطة الاستعادة.",
        ["Windows skipped the restore point: it makes at most one a day."] = "تخطّى Windows نقطة الاستعادة: ينشئ نقطة واحدة يوميًا كحد أقصى.",
        ["Windows skipped the restore point: it makes at most one a day, and the latest is from {0}."] =
            "تخطّى Windows نقطة الاستعادة: ينشئ نقطة واحدة يوميًا كحد أقصى، وآخر نقطة من {0}.",
        ["Windows couldn't create a restore point ({0}). System Protection may be off for drive C: (Control Panel → System → System protection).\n\nInstall anyway?"] =
            "تعذّر على Windows إنشاء نقطة استعادة ({0}). قد تكون حماية النظام متوقفة للقرص C: (لوحة التحكم ← النظام ← حماية النظام).\n\nهل تريد التثبيت على أي حال؟",
        ["Startup apps"] = "تطبيقات بدء التشغيل",
        ["Programs that open when you sign in. Fewer means a faster start and less running in the background. Changes apply at the next sign-in."] =
            "البرامج التي تفتح عند تسجيل الدخول. كلما قلّت كان التشغيل أسرع وقلّ ما يعمل في الخلفية. تُطبَّق التغييرات عند تسجيل الدخول التالي.",
        ["Nothing else starts with Windows."] = "لا شيء آخر يعمل مع بدء Windows.",
        ["Current user"] = "المستخدم الحالي",
        ["All users"] = "كل المستخدمين",
        ["Startup folder"] = "مجلد بدء التشغيل",
        ["Startup folder (all users)"] = "مجلد بدء التشغيل (كل المستخدمين)",
        ["Couldn't change {0}: {1}"] = "تعذّر تغيير {0}: {1}",
        ["Privacy"] = "الخصوصية",
        ["Camera"] = "الكاميرا",
        ["Off switches the webcam off in Windows itself, the same as disabling it in Device Manager: no app or browser can use it until you turn it back on. Stays off after a restart."] =
            "الإيقاف يعطّل الكاميرا في Windows نفسه، مثل تعطيلها من إدارة الأجهزة: لا يستطيع أي تطبيق أو متصفح استخدامها حتى تعيد تشغيلها. تبقى متوقفة بعد إعادة التشغيل.",
        ["No camera found on this PC."] = "لم يُعثر على كاميرا في هذا الجهاز.",
        ["{0}: {1}"] = "{0}: {1}",
        ["on"] = "تعمل",
        ["off"] = "متوقفة",
        ["Turning the camera on…"] = "جارٍ تشغيل الكاميرا…",
        ["Turning the camera off…"] = "جارٍ إيقاف الكاميرا…",
        ["Windows didn't change the camera: {0}"] = "لم يغيّر Windows حالة الكاميرا: {0}",
        ["Raise the CPU's sustained power limit in Performance mode, with a heat safety net"] = "رفع حد طاقة المعالج المستمر في وضع الأداء، مع حماية من الحرارة",
        ["Max GPU performance per game"] = "أقصى أداء لكرت الشاشة لكل لعبة",
        ["Keeps the NVIDIA GPU at full clocks while a chosen game runs"] = "يبقي كرت NVIDIA على أعلى سرعة أثناء تشغيل لعبة تختارها",
        ["See what starts with Windows on the System page, and switch any of it off"] = "اعرض ما يعمل مع بدء Windows في صفحة النظام، وأوقف ما تريد منه",
        ["Camera switch"] = "مفتاح الكاميرا",
        ["Turn the webcam off in Windows itself from Settings → Privacy"] = "أوقف الكاميرا في Windows نفسه من الإعدادات ← الخصوصية",
        ["Restore point before updates"] = "نقطة استعادة قبل التحديثات",
        ["An option on the Drivers page to make a Windows restore point before installing"] = "خيار في صفحة التعريفات لإنشاء نقطة استعادة قبل التثبيت",
        ["Easier navigation"] = "تنقّل أسهل",
        ["The side buttons can be clicked anywhere, the app opens on the Performance page, and it has a new icon"] = "أزرار الشريط الجانبي تُضغط من أي مكان، ويفتح التطبيق على صفحة الأداء، مع أيقونة جديدة",

        // ----- Games page layout -----
        ["Game options"] = "خيارات اللعب",
        ["During play"] = "أثناء اللعب",
        ["After play"] = "بعد اللعب",
        ["Hover over an option to see what it does."] = "مرّر المؤشر فوق أي خيار لمعرفة ما يفعله.",
        ["Click to show or hide this game's settings"] = "اضغط لإظهار إعدادات هذه اللعبة أو إخفائها",
        ["NVIDIA GPU"] = "كرت NVIDIA",

        // ----- Power plan, standby memory, cool-down -----
        ["Tuned power plan in Performance mode"] = "خطة طاقة محسّنة في وضع الأداء",
        ["Faster CPU boost and no parked cores while plugged in, in Performance mode only. Turning it off puts back the values it changed."] =
            "تسريع أعلى للمعالج ودون إيقاف الأنوية أثناء الشحن، في وضع الأداء فقط. الإيقاف يعيد القيم التي غيّرها.",
        ["Already tuned: nothing needed changing."] = "محسّنة مسبقًا: لم يلزم أي تغيير.",
        ["Changed: {0}"] = "تم التغيير: {0}",
        ["Put back the way it was."] = "أُعيدت كما كانت.",
        ["Clear standby memory when a game starts"] = "تفريغ الذاكرة الاحتياطية عند بدء لعبة",
        ["Empties the file data Windows keeps cached in memory, the same as RAMMap's 'Empty Standby List'. Helps games that stutter when memory is nearly full; the first loads right after may be a little slower."] =
            "يفرّغ بيانات الملفات التي يحتفظ بها Windows في الذاكرة، مثل خيار 'Empty Standby List' في RAMMap. يساعد الألعاب التي تتقطع عند امتلاء الذاكرة؛ قد يكون التحميل الأول بعدها أبطأ قليلًا.",
        ["Cool down for 2 minutes after a game closes"] = "تبريد لمدة دقيقتين بعد إغلاق اللعبة",
        ["Runs the fans at full speed for two minutes after a game in this list closes, so the laptop isn't left hot. Starting another game or switching max fan yourself ends it early."] =
            "يشغّل المراوح بأقصى سرعة لمدة دقيقتين بعد إغلاق لعبة من القائمة حتى لا يبقى الجهاز ساخنًا. يتوقف مبكرًا عند تشغيل لعبة أخرى أو تغيير المروحة القصوى يدويًا.",
        [", fans on full for 2 minutes to cool down"] = "، والمراوح بأقصى سرعة لمدة دقيقتين للتبريد",
        ["standby memory cleared"] = "تفريغ الذاكرة الاحتياطية",
        ["Performance boosts"] = "تحسينات للأداء",
        ["A tuned power plan in Performance mode, standby memory cleared when a game starts, and a 2-minute fan cool-down after gaming"] =
            "خطة طاقة محسّنة في وضع الأداء، وتفريغ الذاكرة الاحتياطية عند بدء اللعبة، وتبريد لمدة دقيقتين بعد اللعب",

        // ----- HP fan software -----
        ["HP fan software"] = "برامج المراوح من HP",
        ["HP's own fan and performance software talks to the same BIOS controls as this app, and can undo its fan and mode changes. Turning it off stops it and keeps it from starting; nothing is deleted."] =
            "برامج HP الخاصة بالمراوح والأداء تتحكم في نفس إعدادات الـ BIOS التي يستخدمها هذا التطبيق، وقد تلغي تغييراته على المراوح والأوضاع. الإيقاف يوقفها ويمنع تشغيلها تلقائيًا، دون حذف أي شيء.",
        ["Switched off by Victus Hub, so it can't change the fans or mode. Turn it back on if you want to use Omen Gaming Hub again."] =
            "أوقفها Victus Hub، فلا تستطيع تغيير المراوح أو الوضع. أعد تشغيلها إذا أردت استخدام Omen Gaming Hub مجددًا.",
        ["{0} ({1})"] = "{0} ({1})",
        ["running"] = "يعمل",
        ["not running"] = "متوقف",
        ["Turn off"] = "إيقاف",
        ["Turn back on"] = "إعادة التشغيل",
        ["Some of it didn't change: {0}"] = "لم يتغير بعضها: {0}",
        ["HP fan software check"] = "فحص برامج المراوح من HP",
        ["Finds HP's Omen software that can undo fan and mode changes, and switches it off on the System page"] =
            "يكتشف برامج Omen من HP التي قد تلغي تغييرات المراوح والأوضاع، ويوقفها من صفحة النظام",

        // ----- Smoother gaming -----
        ["Background apps on Efficiency mode while playing"] = "تطبيقات الخلفية على وضع الكفاءة أثناء اللعب",
        ["While any game in this list runs, browsers, game launchers and chat apps (not Discord) get low priority and Windows' Efficiency mode, so they stay off the game's CPU cores. Put back when the game closes."] =
            "أثناء تشغيل أي لعبة من القائمة، تحصل المتصفحات ومشغّلات الألعاب وتطبيقات الدردشة (عدا Discord) على أولوية منخفضة ووضع الكفاءة في Windows، فتبتعد عن أنوية المعالج التي تستخدمها اللعبة. تعود كما كانت عند إغلاق اللعبة.",
        ["Smoother input and network on the charger"] = "إدخال وشبكة أكثر سلاسة عند الشحن",
        ["While plugged in: USB power saving off (fixes a mouse that stutters or briefly freezes) and Wi-Fi at full power (no power-saving ping spikes). On battery nothing changes."] =
            "أثناء توصيل الشاحن: إيقاف توفير طاقة USB (يصلح تقطّع الفأرة أو تجمّدها لحظيًا) وتشغيل Wi-Fi بكامل طاقته (دون ارتفاعات ping بسبب توفير الطاقة). لا يتغير شيء على البطارية.",
        ["Xbox Game Bar background recording"] = "التسجيل في الخلفية لـ Xbox Game Bar",
        ["Game Bar can keep recording the last minutes of gameplay in the background, which costs some FPS. Off stops that and turns off Game Bar clips; Game Bar itself still opens with Win+G."] =
            "يمكن لـ Game Bar أن يسجّل آخر دقائق اللعب في الخلفية، وهذا يقلل بعض الإطارات. الإيقاف يوقف ذلك ويعطّل مقاطع Game Bar، ويبقى Game Bar نفسه يفتح بـ Win+G.",
        ["Couldn't change Game Bar recording: {0}"] = "تعذّر تغيير تسجيل Game Bar: {0}",
        ["Smoother gaming"] = "لعب أكثر سلاسة",
        ["Background apps on Efficiency mode, USB and Wi-Fi power saving off on the charger, and a Game Bar recording switch on the Games page"] =
            "تطبيقات الخلفية على وضع الكفاءة، وإيقاف توفير طاقة USB وWi-Fi عند الشحن، ومفتاح لتسجيل Game Bar في صفحة الألعاب",

        // ----- Settings sections -----
        ["General"] = "عام",
        ["Startup"] = "التشغيل",
        ["Temperature alerts"] = "تنبيهات الحرارة",
        ["Other"] = "أخرى",
        ["Interface language"] = "لغة الواجهة",

        // ----- What's new pop-up -----
        ["Updated"] = "تم التحديث",
        ["New Settings layout"] = "تصميم جديد للإعدادات",
        ["Settings are grouped in a side list, one section at a time"] = "الإعدادات مجمّعة في قائمة جانبية، قسم واحد في كل مرة",
        ["The app can download and install its own updates, checked against the release's checksum"] = "يستطيع التطبيق تنزيل تحديثاته وتثبيتها بنفسه بعد مطابقتها مع checksum الإصدار",
        ["The CPU dial no longer draws outside its card above 50°C, and the Drivers toolbar is no longer cut off"] = "لم يعد مؤشر CPU يُرسم خارج بطاقته فوق 50 درجة، ولم يعد شريط أدوات التعريفات يُقتطع",
        ["A higher power limit and Dynamic Boost for the NVIDIA GPU"] = "حد طاقة أعلى وDynamic Boost لكرت NVIDIA",
        ["The fans quiet down while you're away and come back when you return"] = "تهدأ المراوح أثناء غيابك وتعود عند رجوعك",
        ["A switch for it, and it can turn itself off while the laptop sits idle"] = "مفتاح تشغيل، ويمكنها أن تنطفئ تلقائيًا أثناء خمول الجهاز",
        ["Safer app updates"] = "تحديثات أكثر أمانًا",
        ["Each download is checked against the release's checksum before it's used"] = "يُطابَق كل ملف محمّل مع checksum الإصدار قبل استخدامه",
        ["Fixes"] = "إصلاحات",
        ["The Drivers toolbar is no longer cut off when an update's details are open"] = "لم يعد شريط أدوات التعريفات يُقتطع عند فتح تفاصيل تحديث",
        ["Linen themes"] = "مظهر Linen",
        ["Arabic interface"] = "الواجهة العربية",
        ["Sized to the window"] = "حجم يناسب النافذة",
        ["Battery time per mode"] = "مدة البطارية لكل وضع",
        ["Drive health and BIOS settings"] = "صحة القرص وإعدادات BIOS",
        ["Games add themselves"] = "الألعاب تُضاف تلقائيًا",
        ["Smarter driver checks"] = "فحص أذكى للتعريفات",
        ["Self-update"] = "التحديث الذاتي",
        ["The CPU dial no longer draws outside its card above 50°C"] = "لم يعد مؤشر CPU يُرسم خارج بطاقته فوق 50 درجة",
    };
}
